export enum SocketError {
    LOW_BALANCE = "BUSINESS:LOW_BALANCE",
    LOW_TOURNAMENT_BALANCE = "BUSINESS:LOW_TOURNAMENT_BALANCE",
    ALREADY_EXISTS = "BUSINESS:ALREADY_EXISTS",
    TOO_SHORT = "BUSINESS:TOO_SHORT",
    TOO_LONG = "BUSINESS:TOO_LONG",
    WRONG_PRIVATE_ID = "BUSINESS:WRONG_PRIVATE_ID",
    BLACKLISTED = "BUSINESS:BLACKLISTED",
}